# Generated by Django 5.1.6 on 2025-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('short_des', models.CharField(default='', max_length=200)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blogimages')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
